### PR TITLE
Update 10-get-res.sh

### PR DESCRIPTION
**Pull request by junweizeng**
Maybe we should change the full-width single quotation mark to the half-width single quotation mark here.

### CODE REVIEW

**Comment by arindam-8** [comment]
Hi @Vanish-Zeng ,

Thank you for the PR regarding this. I was wondering if you could explain in a bit more detail, the rationale regarding this change. 

Thanks
Arindam

**Comment by junweizeng** [comment]
Hi @arindam-8 .

Here's a simple example, test.c:

```c
int main
{
    a = 1;
}
```

1. Initially, I compiled it (`gcc test.c`) on an Ubuntu system without full-width single quotation marks (`‘`). The output was as follows:

   > test.c: In function 'main':
   > test.c:3:5: error: 'a' undeclared (first use in this function)
   >     3 |     a = 1;
   >        |     ^
   > test.c:3:5: note: each undeclared identifier is reported only once for each function it appears in
   
   The `In function 'main':` in this case uses a **half-width** single quotation mark.
   
2. However, when I switched to an Ubuntu system with Chinese language support (which includes full-width single quotation marks `‘`), and recompiled it (`gcc test.c`), the output changed to:

   > test.c: In function ‘main’:
   > test.c:3:5: error: ‘a’ undeclared (first use in this function)
   >      a = 1;
   >      ^
   > test.c:3:5: note: each undeclared identifier is reported only once for each function it appears in
   
   The `In function ‘main’:`in this case uses a **full-width** single quotation mark.

**I apologize for the previous commit, which was incorrect.** I think the original `-ve "In function ‘bug’:"` should be retained, and we can add `-ve "In function 'bug':"` after it to enhance the robustness of the program.

**Comment by arindam-8** [comment]
Hi @Vanish-Zeng ,

Many thanks for the response and the explanation. Yes I agree with the idea of making such string matching in these helper scripts more robust. Since there are a few other such places where this would be a feasible change, I would get back to you with some more changes of similar nature.

Would it be possible to move this to an **issue** on this repository so I could then link all the changes to that single issue? It would also help us document such issues.

Thanks
Arindam

**Comment by junweizeng** [comment]
Hi @arindam-8 ,

Thank you for your prompt response to this pull request. I have moved this pull request to an issue on this repository. The issue can be found [https://github.com/srg-imperial/GrayC/issues/5](https://github.com/srg-imperial/GrayC/issues/5). I'm not sure if I need to close this pull request.

Thanks
Jw Zeng.

**Comment by arindam-8** [comment]
Hi @Vanish-Zeng ,

Thank you for moving it to a new issue. I am going to close the PR for now and have a new PR with the change necessary in all the files.

Thanks
Arindam

**Pull request closed without merging**
